### ISSUE TITLE
List of known bugs or things to be added.

### ISSUE THREAD

**Issue by LocalTheSavage** [Warfine/issues#10]
Current things that need to be fixed.
1. Kits death messages need to be enabled.
2. Staff perms need to be fully working.
3. Portals and bugged on HCF, and the end has been added to HCF.
4. Staff chat.
5. Report System.
6. all koths has been pasted in we just need the claims for Koths and roads.
7. End to be claimed.

**Comment by interlagos** [comment]
Bungee needs redone
Kits death messages can be review at a later time
Need to find out if there is an API for dtc

**Comment by interlagos** [comment]
Everything that is my job is done. (If that makes sense)

**Comment by interlagos** [comment]
closing cause above is completed
